import { Point2D } from '../geometry/point';
import { CreaseType } from '../geometry/line';
import { Segment } from '../geometry/segment';
import { GridConfig } from '../geometry/grid';
import { SymmetryAxis } from '../geometry/symmetry';
import { Matrix3x3 } from '../geometry/homography';
import { FractionApproximation } from '../geometry/rational';

export type ToolType =
  | 'select'
  | 'pan'
  | 'crop'
  | 'calibrate'
  | 'point'
  | 'measure'
  | 'line'
  | 'ruler'
  | 'grid'
  | 'symmetry';

export type CPViewMode = 'vector' | 'overlay' | 'image';

export interface ReferencePoint {
  id: string;
  x: number; // normalized paper coordinate [0, 1]
  y: number; // normalized paper coordinate [0, 1]
  xRaw?: number;
  yRaw?: number;
  xGrid?: FractionApproximation;
  yGrid?: FractionApproximation;
  confidence?: number; // 0.0 to 1.0
  residualPx?: number; // error in screen/pixel space
  incidentCreases?: string[];
  label: string;
  color?: string;
  isAutoGenerated?: boolean;
}

export interface CreaseLine extends Segment {
  id: string;
  p1: Point2D;
  p2: Point2D;
  type: CreaseType;
  confirmed: boolean;
  confidence?: number;
  equation?: { a: number; b: number; c: number };
}

export interface MeasurementItem {
  id: string;
  p1: Point2D;
  p2: Point2D;
  label?: string;
}

export interface RulerItem {
  id: string;
  point: Point2D;
  orientation: 'both' | 'horizontal' | 'vertical';
}

export interface CropBox {
  x: number;
  y: number;
  width: number;
  height: number;
  active: boolean;
}

export interface PaperCalibration {
  corners: [Point2D, Point2D, Point2D, Point2D]; // TL, TR, BR, BL
  rectified: boolean;
  homography: Matrix3x3;
  inverseHomography: Matrix3x3;
  aspectRatio: number;
}

export interface CameraState {
  zoom: number; // 0.05 to 64.0
  panX: number;
  panY: number;
  pixelated: boolean;
}

export interface LayerVisibility {
  image: boolean;
  grid: boolean;
  creases: boolean;
  boundary: boolean;
  intersections: boolean;
  points: boolean;
  measurements: boolean;
  rulers: boolean;
  symmetry: boolean;
}

export interface AnalysisReport {
  cpRegionDetected: boolean;
  paperBoundaryDetected: boolean;
  perspectiveCorrected: boolean;
  creaseSegmentsCount: number;
  baseGrid: string;
  intersectionsCount: number;
  referencePointsCount: number;
  visible: boolean;
}

export interface ProjectState {
  version: 1;
  image: {
    url: string | null;
    fileName: string;
    width: number;
    height: number;
    crop: CropBox | null;
  };
  paper: PaperCalibration;
  grid: GridConfig;
  points: ReferencePoint[];
  creases: CreaseLine[];
  measurements: MeasurementItem[];
  rulers: RulerItem[];
  symmetry: {
    enabled: boolean;
    axes: SymmetryAxis[];
  };
  layers: LayerVisibility;
}
